// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFolderTree(arg1) {
  return window['go']['main']['App']['GetFolderTree'](arg1);
}

export function GetWorkingPath() {
  return window['go']['main']['App']['GetWorkingPath']();
}
