// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateDocumentation(arg1:string):Promise<string>;

export function GenerateTests(arg1:string):Promise<string>;

export function GetFileContent(arg1:string):Promise<string>;

export function GetFolderTree(arg1:string):Promise<string>;

export function GetWorkingPath():Promise<string>;
