// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateDocumentation(arg1) {
  return window['go']['main']['App']['GenerateDocumentation'](arg1);
}

export function GenerateTests(arg1) {
  return window['go']['main']['App']['GenerateTests'](arg1);
}

export function GetFileContent(arg1) {
  return window['go']['main']['App']['GetFileContent'](arg1);
}

export function GetFolderTree(arg1) {
  return window['go']['main']['App']['GetFolderTree'](arg1);
}

export function GetWorkingPath() {
  return window['go']['main']['App']['GetWorkingPath']();
}
